import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import NavbarV2 from "@/components/custom/NavbarV2";
import Footer from "@/components/custom/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html>
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
        <link rel="shortcut icon" href="portfolio_icon.png" type="image/x-icon" />
      </head>
      <body className="overflow-x-hidden">
        {/* <Navbar /> */}
        <NavbarV2 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
